"""Write the Windows version resource stamped into ghmanage.exe.

Without it the built .exe has no product name, no version, and no publisher:
Properties > Details is blank, and a user who wants to know which build they are
running has nothing to look at outside the app. Velopack stamps its own Setup.exe
but not the packaged app, so this fills that gap.

The version comes from version.py, the same source CI checks the release tag
against. Run from the repo root:

    python assets\\make_version_info.py

Writes build\\version_info.txt, which build.bat feeds to PyInstaller's
--version-file.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from version import __version__  # noqa: E402

COMPANY = "Kelly Ford"
PRODUCT = "GHManage"
DESCRIPTION = "GHManage - GitHub issues, pull requests, and repository viewer"
COPYRIGHT = "Copyright (c) Kelly Ford. MIT License."

TEMPLATE = """\
# Auto-generated by assets/make_version_info.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tup},
    prodvers={tup},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{company}'),
         StringStruct('FileDescription', '{description}'),
         StringStruct('FileVersion', '{version}'),
         StringStruct('InternalName', 'ghmanage'),
         StringStruct('LegalCopyright', '{copyright}'),
         StringStruct('OriginalFilename', 'ghmanage.exe'),
         StringStruct('ProductName', '{product}'),
         StringStruct('ProductVersion', '{version}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def as_tuple(version: str) -> tuple[int, int, int, int]:
    """Windows wants four integers; SemVer gives three (plus any prerelease)."""
    parts = [int(p) for p in re.findall(r"\d+", version)][:4]
    parts += [0] * (4 - len(parts))
    return tuple(parts)  # type: ignore[return-value]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(ROOT / "build" / "version_info.txt"),
                        help="output path (default: build/version_info.txt)")
    args = parser.parse_args()

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        TEMPLATE.format(tup=as_tuple(__version__), version=__version__, company=COMPANY,
                        product=PRODUCT, description=DESCRIPTION, copyright=COPYRIGHT),
        encoding="utf-8")
    print(f"Wrote {out} (version {__version__})")


if __name__ == "__main__":
    main()
